# -*- coding: utf-8 -*-
"""Data_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zUe053zjURb7HgzQ2-7gBmhkay2GpHmm
"""

#Importing the necessary libraries
import pandas as pd

#Loading both dataset
train_data = pd.read_csv('/content/train.csv')
test_data = pd.read_csv('/content/test.csv')

#Combining the two datasets to form one complete dataframe for data cleaning process
df = pd.concat([train_data,test_data],ignore_index=True)
df

#Previewing the whole data set to get a glimpse of the columns and rows
print(df.to_string())

#Removing duplicates
df=df.drop_duplicates()
df

#dropping columns that are not necessary when performing data cleaning.
df=df.drop(columns=['Ticket','Cabin'])
df

# Stanadardizing the column name to a more neater look.
# Split the 'Name' column into two new columns: 'Surname' and 'OfficialName'
df[['Surname','OfficialName',]] = df['Name'].str.split(',',expand=True)
df

#Dropping the column 'Name'
df= df.drop(columns=['Name'])
df

#Checking the sum of null values in each column
df.isnull().sum()

#Dropping null values in each column throughout the dataframe
df=df.dropna(subset=['Survived','Age','Fare','Embarked'])

#Reseting the index for the dataframe
df=df.reset_index(drop=True)
df

